# .github/workflows/build-addons.yml
name: Build & Publish HAOS Add-ons

on:
  push:
    branches: [main]
    paths:
      - "addon-postgres-pgvector/**/**"
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'If "true", build only (no push)'
        required: false
        default: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        addon: [postgres_pgvector, pgvector_tester]

    env:
      DRY_RUN: ${{ github.event.inputs.dry_run || 'false' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Debug - Show files
        run: |
          pwd
          ls -l addon-postgres-pgvector/${{ matrix.addon }}

      - name: Check for "image" in config.json
        id: config_check
        run: |
          echo "Checking addon-postgres-pgvector/${{ matrix.addon }}/config.json for an 'image' field..."
          if jq -e '.image' addon-postgres-pgvector/${{ matrix.addon }}/config.json >/dev/null 2>&1; then
            echo "skip=false" >> $GITHUB_OUTPUT
          else
            echo "skip=true" >> $GITHUB_OUTPUT
          fi

      - name: Skip notice
        if: steps.config_check.outputs.skip == 'true'
        run: echo "⚠️ addon-postgres-pgvector/${{ matrix.addon }} has no 'image' property; skipping build."

      - name: Log in to GHCR
        if: env.DRY_RUN == 'false' && steps.config_check.outputs.skip == 'false'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push "${{ matrix.addon }}"
        if: steps.config_check.outputs.skip == 'false'
        uses: docker/build-push-action@v4
        with:
          context: ./addon-postgres-pgvector/${{ matrix.addon }}
          file: ./addon-postgres-pgvector/${{ matrix.addon }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ env.DRY_RUN == 'false' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.addon }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.addon }}:${{ github.sha }}
